import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

DEFAULT_DATABASE_PATH = os.path.join(BASE_DIR, "cutting_app.db")
DATABASE_ENV_VAR = "CUTTING_DB_PATH"


def get_database_path() -> str:
    return os.getenv(DATABASE_ENV_VAR, DEFAULT_DATABASE_PATH)

DEFAULT_CUT_WIDTH = 3.0
DEFAULT_EDGE_OFFSET = 10.0
DEFAULT_GUILLOtINE_DEPTH = float("inf")

GA_POPULATION_SIZE = 50
GA_GENERATIONS = 200
GA_MUTATION_RATE = 0.05
GA_CROSSOVER_RATE = 0.85
GA_TOURNAMENT_K = 3

SA_INITIAL_TEMP = 1000.0
SA_COOLING_RATE = 0.995
SA_MIN_TEMP = 1.0

AUTO_SAVE_INTERVAL = 300

MAX_CUTTING_TIME_SECONDS = 60
MAX_CUTTING_PIECES = 200
